### ISSUE TITLE
Eject doesn't work

### ISSUE THREAD

**Issue by stereobooster** [kitze/create-react-app#16]
I suppose this is a bit strange request for eject feature in repo which suppose to prevent eject, but reporting it in case you are not aware.

Trying to get to work this thing https://github.com/react-toolbox/react-toolbox-example/pull/35. I want to eject to try to fix it on ejected version and then come up with some solution without eject.

### Description

```
npm run eject

npm start
> react-toolbox-example@0.12.0 start /Users/**/my/react-toolbox-example
> node scripts/start.js

module.js:440
    throw err;
    ^

Error: Cannot find module './get-custom-config'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/**/my/react-toolbox-example/config/webpack.config.dev.js:11:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/**/my/react-toolbox-example/scripts/start.js:20:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)

npm ERR! Darwin 15.6.0
npm ERR! argv "/opt/nodes/6.1.0/bin/node" "/opt/boxen/nodenv/versions/6.1.0/bin/npm" "start"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! react-toolbox-example@0.12.0 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-toolbox-example@0.12.0 start script 'node scripts/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-toolbox-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-toolbox-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-toolbox-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/**/my/react-toolbox-example/npm-debug.log
```

**Comment by stereobooster** [comment]
Added PR, so closing issue
