### ISSUE TITLE
problem with tranforming styles in tests

### ISSUE THREAD

**Issue by andrzejsliwa** [kitze/create-react-app#51]
steps to reproduce:

```bash
$ create-react-app my-app --scripts-version custom-react-scripts
$ cd my-app
$ yarn test
```

result:

```bash
 FAIL  src/App.test.js
  ● Test suite failed to run

    /my-app/src/App.less:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){.App {
                                                                                             ^
    SyntaxError: Unexpected token .
    SyntaxError: Unexpected token .

      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:316:10)
      at Object.<anonymous> (src/App.js:5:286)
      at Object.<anonymous> (src/App.test.js:3:38)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.416s
Ran all test suites.

Watch Usage
 › Press p to filter by a filename regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.
```

**Comment by sampi** [comment]
This sounds the same as #49

**Comment by igorsantos07** [comment]
definitely a dup
